version: '3.4'
services:
  #   nginx:
  #     image: nginx:latest
  #     container_name: webserver
  #     restart: always
  #     ports:
  #       - 80:80
  #       - 443:443
  #     volumes:
  #       - ./config/nginx.conf:/etc/nginx/nginx.conf
  #       - certbot-etc:/etc/letsencrypt
  #       - certbot-var:/var/lib/letsencrypt
  #       - web-root:/var/www/html
  #     links:
  #       - api
  #     depends_on:
  #       - api
  app:
    image: berichtgeving/berichtgeving-frontend:18
    container_name: client
    ports:
      - '3001:3001'
    expose:
      - '3001'
    volumes:
      - ~/build:/var/www/html
    depends_on:
      - 'api'
  api:
    image: berichtgeving/berichtgeving-backend:15
    container_name: server
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - db
    links:
      - db
    environment:
      DB_HOSTNAME: db
  #   certbot:
  #     image: certbot/certbot
  #     container_name: certbot
  #     volumes:
  #       - certbot-etc:/etc/letsencrypt
  #       - certbot-var:/var/lib/letsencrypt
  #       - web-root:/var/www/html
  #     depends_on:
  #       - nginx
  #     command: certonly --webroot --webroot-path=/var/www/html --email uzunaliegemen@gmail.com --agree-tos --no-eff-email --force-renewal  -d www.cyfamilia.nl
  db:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=pingping
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: {}
  certbot-etc:
  certbot-var:
  web-root:
